name: Feature request
description: Suggest a docs site or playground improvement
labels: ["needs triage"]
assignees: ["DerekCorniello"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
